const DummyData = [
  {
    id: 1,
    headNumber: 1,
    contents: '리워드콘발행내용1',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 300,
    companyName: 'ㅇㅇ기업',
    points: 100000,
    produced: 1500,
    use: 2500,
    result: '전송성공',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 2,
    headNumber: 2,
    contents: '리워드콘발행내용2',
    transferNumber: 400,
    days: '21-07-22 13:20',
    published: 500,
    companyName: 'ㅁㅁ기업',
    points: 100000,
    produced: 1500,
    use: 2500,
    result: '전송성공',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 3,
    headNumber: 3,
    contents: '리워드콘발행내용3',
    transferNumber: 400,
    days: '21-07-22 13:20',
    published: 500,
    companyName: 'ㄴㄴ기업',
    points: 100000,
    produced: 1500,
    use: 2500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 4,
    headNumber: 4,
    contents: '리워드콘발행내용4',
    transferNumber: 400,
    days: '21-07-22 13:20',
    published: 500,
    companyName: 'ㄷㄷ기업',
    points: 100000,
    produced: 500,
    use: 100,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 5,
    headNumber: 5,
    contents: '리워드콘발행내용5',
    transferNumber: 400,
    days: '21-07-22 13:20',
    published: 500,
    companyName: 'ㄹㄹ기업',
    points: 100000,
    produced: 3500,
    use: 2500,
    result: '전송성공',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 6,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 7,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 10,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 11,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 12,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 13,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 14,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 15,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 16,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 17,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 18,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 19,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 20,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
  {
    id: 21,
    headNumber: 6,
    contents: '리워드콘발행내용6',
    transferNumber: 200,
    days: '21-07-22 13:20',
    published: 100,
    companyName: 'ㅂㅂ기업',
    points: 80000,
    produced: 1200,
    use: 500,
    result: '전송실패',
    writer: 'admin',
    title: '공지내용',
  },
];

export default DummyData;

export const Images = [
  {
    id: 1,
    headNumber: 1,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 2,
    headNumber: 2,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 3,
    headNumber: 3,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 4,
    headNumber: 4,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 5,
    headNumber: 5,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 6,
    headNumber: 6,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 7,
    headNumber: 7,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 8,
    headNumber: 8,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 9,
    headNumber: 9,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 10,
    headNumber: 10,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 11,
    headNumber: 11,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 12,
    headNumber: 12,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 13,
    headNumber: 13,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 14,
    headNumber: 14,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 15,
    headNumber: 15,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
  {
    id: 16,
    headNumber: 16,
    img: require('../../assets/rkeep_pic.jpg').default,
    result: '전송성공',
  },
];
